apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-requests-controller
  name: resource-requests-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-requests-controller
  template:
    metadata:
      labels:
        app: resource-requests-controller
    spec:
      containers:
      - image: devopyio/resource-requests-admission-controller:5e3b111cbcf8
        name: resource-requests-controller
        env:
        - name: TLS_CERT_FILE
          value: "/etc/tls/cert.pem"
        - name: TLS_KEY_FILE
          value: "/etc/tls/key.pem"
        - name: EXCLUDE_NAMESPACES
          value: "kube-system,kube-public,sys-ingress,sys-mon,default" 
        - name: EXCLUDE_NAMES
          value: "pod.kube-system,pod2.kube-system"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: /etc/tls/
      volumes:
      - name: tls
        secret:
          secretName: resource-requests-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resource-requests-controller
  name: resource-requests-controller
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: resource-requests-controller
