apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
 name: resource-requests-controller
webhooks:
 - name: resource-requests-controller.devopy.io
   clientConfig:
     service:
       name: resource-requests-controller
       namespace: kube-system
       path: "/"
     caBundle: "TODO"
   rules:
    - operations: ["CREATE","UPDATE"]
      apiGroups: ["*"]
      apiVersions: ["*"]
      resources: ["pods","deployments","statefulsets","daemonsets","cronjobs","jobs","persistentvolumeclaims"]
   failurePolicy: Ignore
